name: meme-recommender
channels:
  - conda-forge
dependencies:
  - python
  - tensorflow[and-cuda]
  - scikit-learn
  - scikit-image
  - opencv
  - ipykernel
  - pip
  - pip:
    - keras # to override tensorflow version with Keras 3